---
title: "BIOS 600: Principles of Statistical Inference"
tbl-colwidths: [5,10,30,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week     | Date  | Topic  |  Slides | AE |  Lab  | HW   |  Exam  |  Project  |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|
|  1  | Tue, Aug 20 | Welcome! + Course Overview                                                                 |        [🖥️](/slides/lec-1.html "lecture 1s"){aria-label="s"}    |                |       |    |     |    |
|    | Tue, Aug 20 | Lab 1: Meet the toolkit                        |        |          |    [💻](/labs/lab-1.html "Lab 1 Instructions"){aria-label="Lab 1 instructions"}    |  |    |  |
|    | Thu, Aug 22 | Ch 1: Measurement   | [🖥️](/slides/lec2-measure-ch1-speaker.html "Lecture slides"){aria-label="Lecture 1 slides"} |       [📋](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"}       |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [2](/weeks/week-2.html)  | Tue, Aug 27 | Lab 2: Exploring data                                                                  |              [🖥️](/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}               |                                                                                                                 |                                                               [💻](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |

:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
